#! /bin/bash

export INSTANCE_NAME="rtb-command" 
export INSTANCE_TYPE="t2.micro"
export COMMAND="git clone https://github.com/RenderToolbox3/rtb-support.git"
export TERMINATE="no"
export AMI_ID="ami-7172b611"
export DISK_GB=20

mkdir -p ~/rtb-logs
./run-render-instance

