#! /bin/bash

export INSTANCE_NAME="vwcc-100-recipe-check-m4-2xlarge" 
export INSTANCE_TYPE="m4.2xlarge"
export COMMAND="docker run \
  --rm \
  -v \"/usr/local/MATLAB/R2015b\":/usr/local/MATLAB/from-host \
  -v /home/ubuntu:/home/ubuntu \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --net=\"host\" \
  -e \"STARTUP=/home/ubuntu/MATLAB/startup\" \
  -e \"TOOLBOXES={'VirtualWorldColorConstancy', 'isetbio'}\" \
  -e \"COMMAND=RunToyVirtualWorldRecipes('luminanceLevels', [.2 .2119 .2245 .226 .2379 .2520 .2553 .267 .2829 .2884], 'reflectanceNumbers', 1:10, 'executeWidth', 640, 'executeHeight', 480, 'analyzeWidth', 640, 'analyzeHeight', 480)\" \
  -e \"OUTPUT_SCRATCH=/home/ubuntu/render-toolbox-working\" \
  -e \"OUTPUT_BUCKET=s3://render-toolbox-test/vwcc-100-recipe-check-m4-2xlarge\" \
  ninjaben/rtb-support"

mkdir -p ~/rtb-logs
./run-render-instance 2>&1 > ~/rtb-logs/vwcc-100-recipe-check-m4-2xlarge.log &

